language: python
services:
  - mongodb
python: 2.7
env:
  matrix:
  - TOXENV=py27
  global:
    secure: MLEL+S74y9XBcNGuHN5PODNKTGRISRCQURO7j0t+sPaRTSQEjts3DdGaDRMpVlIIvSmWuJMuRwXQXRMLkJ2FmmFF1BLxGk9aVQwXtsp2F58Gqb7wcIJx9mf1AuXVocCvGB6jm/aHHl7c/lMtA6P/aqjcLqTMHW6a35PQYqk5A2jhj1F7ouo1BT93MZ7NO8ggZwebz5jemjhRqG9EpqUtuKOS6ocxmWVzp+dp/0GZ9M9L0XpcjiNv13cDpeSfLaBK5xnEk9ZGHZAid6dMWWS2LeAwxNAYqpPHuOr8WaCIdELxfJZzWbgYSTSLQ7wqBtDq1MLdoaO1FhHxAaFK6o5LnV6wxVcKKpM+oId/Dt0eVqFmykT9mCiWoEIdmuk9u4iwK3823OiCdXFcFrQI6J27vmL4YzVqRAEFhuuIe9hrxOoi0/x4Pshyq5bpD3c24nFLt5BIsCzrFXFBERBTn1BAHN6JT2yYm35IMASsXvtmxhuMWXb+PGUgW80gy09ozmWWxQJj+edIpwr0Zj7evb4S7TBS1lE4rlsQTlLCeRs1TOQhZK0yq9kBfiHF4z+ufPahmOAfqWNTLCvaRNCVDXix6zLH09Vy3m/y/wTHQvZ4TqcfChh8UhiV+DN0hMrvELXhDvpHJMlUvYemc+20Ei2kHW6qMMAoQl1oJZsB1h0S8qY=
install:
- pip install -U tox
script:
- tox
notifications:
  slack: crim-ca:A7jqt2VJWnPwN6A3AZXJ40gt
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: crim-ca
  password:
    secure: YoO2N4978Aj63fbhNQwRb9KzvCS30v3nQLS/8CpuhIfB9azj4tynPHlll/8eyDKjlqytqPphzonVpDBjRhD+UnDrTBSdls3Vtz2YgCedcg/ucUpvStgWXhe2gYdUIQ8pOTENu+5/yKS+6eRnTpbdL8wm4J1na1w0kf9PrK0b7tvTX7el3w8GYSoiXc51mjrvZBcLOmKYI7DnybcHwy2WS08e/n42Yywp+qu4U4qoquF2BUP7AxjjrlCCv2m05oapwWhW/lGUG+mFSqwK/bj2PtcJGtfbqGto8dJxk4tWwKNP8KDkt+rATRqPYmNdDdk82BdzaNEeTEvYU5cToOX/6/3uPY66zzKnDGAJfXC8nppo9O2iCVrUqIBFxZMtaXluXNqYmFl58jaY7MD86LToOye4l0AKsclXbAav9t+HuSomCiITQuDxRENT/CxeN7++LybXUSoMiEsMcNuzoxP0MKWQ+EH7iYT75q++g6wI+Vk2QmaP3I9zWuasZUHsJWwv+fNS5nHNaG2LgqtF+APsEeYExXDgz80RZh11Cv++L/vhFZ9tV0QpmefIG/gZ3h0BY2X4Bl9KmGsefv/bgo5XmylR+qPC/Hxd7MlQBo0vbgpJpy5ysD6LRemdwNeWD4fa6pBqCh29LV64J2JfGgWqcEYUKAb8D0X/dQ3SCHC6q/M=
  on:
    tags: true
