language: python
python: 2.7
env:
  matrix:
  - TOXENV=py27
  global:
    secure: MLEL+S74y9XBcNGuHN5PODNKTGRISRCQURO7j0t+sPaRTSQEjts3DdGaDRMpVlIIvSmWuJMuRwXQXRMLkJ2FmmFF1BLxGk9aVQwXtsp2F58Gqb7wcIJx9mf1AuXVocCvGB6jm/aHHl7c/lMtA6P/aqjcLqTMHW6a35PQYqk5A2jhj1F7ouo1BT93MZ7NO8ggZwebz5jemjhRqG9EpqUtuKOS6ocxmWVzp+dp/0GZ9M9L0XpcjiNv13cDpeSfLaBK5xnEk9ZGHZAid6dMWWS2LeAwxNAYqpPHuOr8WaCIdELxfJZzWbgYSTSLQ7wqBtDq1MLdoaO1FhHxAaFK6o5LnV6wxVcKKpM+oId/Dt0eVqFmykT9mCiWoEIdmuk9u4iwK3823OiCdXFcFrQI6J27vmL4YzVqRAEFhuuIe9hrxOoi0/x4Pshyq5bpD3c24nFLt5BIsCzrFXFBERBTn1BAHN6JT2yYm35IMASsXvtmxhuMWXb+PGUgW80gy09ozmWWxQJj+edIpwr0Zj7evb4S7TBS1lE4rlsQTlLCeRs1TOQhZK0yq9kBfiHF4z+ufPahmOAfqWNTLCvaRNCVDXix6zLH09Vy3m/y/wTHQvZ4TqcfChh8UhiV+DN0hMrvELXhDvpHJMlUvYemc+20Ei2kHW6qMMAoQl1oJZsB1h0S8qY=
install:
- pip install -U tox
script:
- tox
notifications:
  slack: crim-ca:A7jqt2VJWnPwN6A3AZXJ40gt
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: crim-ca
  password:
    secure: OPVN84qLimQt7BY/lMS0bK/TzZgRxPSQxkbzkwoQ3jMCHCCg5gcSC3OnivyCq3tb7zhf/1szNHhV2rA15KakFzdNDJSvKhXexeLkU3TcOEkwUYBPQmUaGfpF5Vy53zerPdxRlOUQegg0oYYXKVMDN4cJ5vydHToaiPYiDwzV8sGYpNmKFdiO+nEJ2Sze6BrorAUJVYBbUmeBk+XqsyeeYwqtuUESZJyVvhwcjIWwNUz1yaysbN6mMhuxsmybqTwWkU7JOPK91gKrSWo96Oom9eTQ/Yqvq8sKsz58CzkZm7OLzDEtX6yjs3jZzuEHkMSwGWY3mahMuafflyFqs+q5wj/i1/NcXdWs01GXKjCUmsn4qUE4Nvpw05QKuPPcVr6BLCDk9bFHfyMlvQhHqB81IA0LqBw5Y1lP+HboNHmzlp0LtGcxgcvOq/96XL+HzPGWbi2rvAwof+ED2va/KS1xfOcXrOgXauFESLRbEAgtE04idFBtkT1Hcvaaom5eBd2K43bsn+pVkRG/YeYDuZMdfVwZDf1YDJjTD/pV2fczXgcgrsfSh4ld/WTQ1sAjnxoZHypQ5Xg8NKhrKGubhucHzWZZ6YwMgG5dMlDDRGoj+ERkZ7zJMO4wTBolIfiyG2T8gYQvqXrnViHD8k6tDR1eO74TeCLQYXYcPWkPKWVouDw=
  on:
    tags: true
